flush ruleset

table inet filter {
  chain input {
    type filter hook input priority filter; policy drop;
    iifname "lo" accept
    ct state established,related accept
    ct state invalid drop
    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept
    iifname "reka0" ip saddr 10.77.0.0/24 ip daddr 10.77.0.1 icmp type echo-request accept
    tcp dport 22 ct state new limit rate 30/minute burst 15 packets accept
    tcp dport { 80, 443 } accept
    udp dport 443 accept
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    ct state established,related accept
    iifname "reka0" oifname "ens3" ip saddr 10.77.0.0/24 accept
    iifname "ens3" oifname "reka0" ip daddr 10.77.0.0/24 ct state established,related accept
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}

table ip nat {
  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;
    oifname "ens3" ip saddr 10.77.0.0/24 masquerade
  }
}
